In [1]:
import torch

In [2]:
torch.__version__

'1.12.1+cu113'

In [3]:
x = [[0, 1], [2, 3]]

In [4]:
print('x: ', x)
print('type: ', type(x))

x:  [[0, 1], [2, 3]]
type:  <class 'list'>


In [8]:
x_tensor = torch.tensor(x)
print('x_tensor: ', x_tensor)
print('type: ', type(x_tensor))

x_tensor:  tensor([[0, 1],
        [2, 3]])
type:  <class 'torch.Tensor'>


In [9]:
import numpy as np

In [10]:
x_numpy = np.array(x)
print(type(x_numpy))

<class 'numpy.ndarray'>


In [11]:
numpy_to_tensor = torch.from_numpy(x_numpy)
print(type(numpy_to_tensor))

<class 'torch.Tensor'>


In [13]:
tensor_to_numpy = numpy_to_tensor.numpy()
print(type(tensor_to_numpy))

<class 'numpy.ndarray'>


In [16]:
rand_tensor = torch.rand(2, 2)
print(rand_tensor.shape)
print(rand_tensor)

torch.Size([2, 2])
tensor([[0.7225, 0.0703],
        [0.0690, 0.0138]])


In [19]:
tensor_zero = torch.zeros(3, 3, 3)
tensor_zero

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [20]:
tensor_one = torch.ones(3, 3, 3)
tensor_one

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [23]:
x_tensor = torch.tensor([[1, 2, 3],
                         [4, 5, 6]])

In [24]:
print('first row: ', x_tensor[0])

first row:  tensor([1, 2, 3])


In [25]:
print('last row: ', x_tensor[-1])

last row:  tensor([4, 5, 6])


In [26]:
print('first column: ', x_tensor[:, 0])

first column:  tensor([1, 4])


In [27]:
print('last column: ', x_tensor[:, -1])

last column:  tensor([3, 6])


In [29]:
print('second row, last column: ', x_tensor[1, -1])
print('second row, last column: ', x_tensor[1, 2])

second row, last column:  tensor(6)
second row, last column:  tensor(6)


In [30]:
print('x_tensor before: ', x_tensor)

x_tensor before:  tensor([[1, 2, 3],
        [4, 5, 6]])


In [31]:
x_tensor[1, 1] = 0
print('x_tensor after: ', x_tensor)

x_tensor after:  tensor([[1, 2, 3],
        [4, 0, 6]])


In [32]:
x_tensor[1, 1] = 5

In [33]:
print('x_tensor before: ', x_tensor)
x_tensor[1] = 0
print('x_tensor after: ', x_tensor)

x_tensor before:  tensor([[1, 2, 3],
        [4, 5, 6]])
x_tensor after:  tensor([[1, 2, 3],
        [0, 0, 0]])


In [35]:
x_tensor[1] = torch.tensor([4, 5, 6])

In [36]:
concat_dim0 = torch.cat([x_tensor, x_tensor], dim=0)
print(concat_dim0)

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]])


In [37]:
concat_dim1 = torch.cat([x_tensor, x_tensor], dim=1)
print(concat_dim1)

tensor([[1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6]])


In [38]:
concat_dim0.shape

torch.Size([4, 3])

In [39]:
concat_dim1.shape

torch.Size([2, 6])

In [43]:
print("2행 3열을 3행 2열로")
x_tensor.reshape(3, 2)
x_tensor.shape

2행 3열을 3행 2열로


torch.Size([2, 3])

In [42]:
x_tensor_reshape32 = x_tensor.reshape(3, 2)
x_tensor_reshape32.shape

torch.Size([3, 2])

In [46]:
mat_mul = x_tensor.matmul(x_tensor.T)
mat_mul

tensor([[14, 32],
        [32, 77]])

In [47]:
element_product = x_tensor * x_tensor
element_product

tensor([[ 1,  4,  9],
        [16, 25, 36]])