In [1]:
import tensorflow as tf
from tensorflow.keras import Model, layers
import numpy as np

In [32]:
class NN(Model):
    def __init__(self, hidden_1, hidden_2, num_classes):
        super(NN, self).__init__()

        self.mlp1 = layers.Dense(hidden_1, activation=tf.nn.relu)
        self.mlp2 = layers.Dense(hidden_2, activation='relu')
        self.mlp3 = layers.Dense(num_classes)

    def call(self, x):
        out = self.mlp1(x)
        out = self.mlp2(x)
        out = self.mlp3(x)
        out = tf.nn.softmax(out)

        return out

In [33]:
hidden_1 = 128
hidden_2 = 256
num_classes = 10

In [34]:
model = NN(hidden_1, hidden_2, num_classes)

In [13]:
data = tf.random.normal(shape=(1, 28*28), mean=0., stddev=1.)
print(data.shape)

(1, 784)


In [14]:
pred = model(data)

In [15]:
y_hat = tf.argmax(pred, 1)
y_hat

<tf.Tensor: shape=(1,), dtype=int64, numpy=array([9])>

In [16]:
pred

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.00496942, 0.04893567, 0.02671502, 0.01055805, 0.14452304,
        0.00264209, 0.06102099, 0.08250835, 0.12597252, 0.49215484]],
      dtype=float32)>

In [17]:
x = tf.random.normal(shape=(3, 28, 28), mean=0., stddev=1.)

In [18]:
fc_layer = layers.Dense(100)
x_after_fc = fc_layer(tf.reshape(x, (-1, 28*28)))
x_after_fc.shape

TensorShape([3, 100])

In [21]:
x_after_fc[0][:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-1.518773  ,  0.1439358 , -0.78894365,  0.58153224,  1.8042809 ,
        0.0628072 , -0.36831152,  1.184992  ,  3.1684437 ,  1.6085615 ],
      dtype=float32)>

In [23]:
fc_layer = layers.Dense(100, activation='relu')
x_after_fc = fc_layer(tf.reshape(x, (-1, 28*28)))
x_after_fc.shape

TensorShape([3, 100])

In [24]:
x = tf.random.normal(shape=(1, 10), mean=0., stddev=1.)

pred = tf.nn.softmax(x)
print(pred)

tf.Tensor(
[[0.02094794 0.05811414 0.05400216 0.07192472 0.02147858 0.12263405
  0.10065715 0.37727714 0.0482754  0.12468867]], shape=(1, 10), dtype=float32)


In [30]:
class NN2(Model):
    def __init__(self, hidden_1, hidden_2, num_classes):
        super(NN2, self).__init__()
        
        self.sequential = tf.keras.Sequential([
            layers.Dense(hidden_1, activation=tf.nn.relu),
            layers.Dense(hidden_2, activation='relu'),
            layers.Dense(num_classes, activation=tf.nn.softmax)
        ])

    def call(self, x):
        out = self.sequential(x)
        return out

In [35]:
hidden_1 = 128
hidden_2 = 256
num_classes = 10

model = NN2(hidden_1, hidden_2, num_classes)

In [37]:
model = tf.keras.Sequential()
model.add(layers.Dense(hidden_1, activation='relu'))
model.add(layers.Dense(hidden_2, activation='relu'))
model.add(layers.Dense(num_classes, activation='softmax'))

In [39]:
model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])

In [40]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [41]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
              metrics=['accuracy'])